# Generated by Django 5.1 on 2024-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('Published_on', models.DateTimeField(auto_now=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('Salary', models.IntegerField(default=1)),
                ('Job_Nature', models.CharField(choices=[('FULL TIME', 'FULL TIME'), ('PART TIME', 'PART TIME')], max_length=50)),
            ],
        ),
    ]
