# Generated by Django 5.1 on 2024-09-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
